services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pocdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: d
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pocdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: d
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  pgdata:
